### ISSUE TITLE
Block pattern

### ISSUE THREAD

**Issue by ArtMin96** [customberg/customberg-php#1]
Hello. Is it possible to use block patterns? Also, can you open the discussion section so that a new issue is not created in case of questions?

**Comment by AndreiTelteu** [comment]
Hi !
I activated discussions.
Unfortunately block patters are not supported.
This package is based on [VanOns/laraberg](https://github.com/VanOns/laraberg) which does not have support for this.
Maybe open a issue there ?

**Comment by ArtMin96** [comment]
It seems that package is not maintainable. Someone asked a question on that topic, but there was no answer.

**Comment by ArtMin96** [comment]
Sorry for not asking a question related to your package, but do you know what is the alternative to `setContent()`, because it doesn't work?

**Comment by AndreiTelteu** [comment]
I saw you issue with setcontent.
I tried changing the .value or the .innerHTML  and then triggering a change event but nothing works.
Maybe something with dispatch().

**Comment by AndreiTelteu** [comment]
@ArtMin96 Take a look here:
https://github.com/VanOns/block-editor/blob/main/src/components/Editor.tsx#L29

```js
const { setBlocks } = useDispatch('block-editor');
setBlocks([]);
```
blocks is an array.
to convert a string in this form of array i think you need to use parse `import { parse, serialize } from '@wordpress/blocks'`

**Comment by AndreiTelteu** [comment]
I found the solution. I posted to your original issue so other people can find it there

https://github.com/VanOns/laraberg/issues/181#issuecomment-1377989942

```js
const { dispatch } = window.Laraberg.wordpress.data;
const { parse } = window.Laraberg.wordpress.blocks;
window.Laraberg.setContent = (input) => {
    dispatch('block-editor').setBlocks(parse(input));
};
// window.Laraberg.setContent('<!-- wp:paragraph --> <p>dada</p> <!-- /wp:paragraph -->');
```

**Comment by ArtMin96** [comment]
@AndreiTelteu Thank you so much. It works
